# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dog_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protoc.dogs_pb2 as dogs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dog_service.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x64og_service.proto\x1a\ndogs.proto\"\"\n\x0fServiceResponse\x12\x0f\n\x07message\x18\x01 \x01(\t20\n\nDogService\x12\"\n\x06PetDog\x12\x04.Dog\x1a\x10.ServiceResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[dogs__pb2.DESCRIPTOR,])




_SERVICERESPONSE = _descriptor.Descriptor(
  name='ServiceResponse',
  full_name='ServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ServiceResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['ServiceResponse'] = _SERVICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceResponse = _reflection.GeneratedProtocolMessageType('ServiceResponse', (_message.Message,), dict(
  DESCRIPTOR = _SERVICERESPONSE,
  __module__ = 'dog_service_pb2'
  # @@protoc_insertion_point(class_scope:ServiceResponse)
  ))
_sym_db.RegisterMessage(ServiceResponse)



_DOGSERVICE = _descriptor.ServiceDescriptor(
  name='DogService',
  full_name='DogService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=69,
  serialized_end=117,
  methods=[
  _descriptor.MethodDescriptor(
    name='PetDog',
    full_name='DogService.PetDog',
    index=0,
    containing_service=None,
    input_type=dogs__pb2._DOG,
    output_type=_SERVICERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOGSERVICE)

DESCRIPTOR.services_by_name['DogService'] = _DOGSERVICE

# @@protoc_insertion_point(module_scope)
