# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dogs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dogs.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\ndogs.proto\"/\n\x03\x44og\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x62reed\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x62\x06proto3')
)




_DOG = _descriptor.Descriptor(
  name='Dog',
  full_name='Dog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Dog.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='breed', full_name='Dog.breed', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='Dog.age', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['Dog'] = _DOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dog = _reflection.GeneratedProtocolMessageType('Dog', (_message.Message,), dict(
  DESCRIPTOR = _DOG,
  __module__ = 'dogs_pb2'
  # @@protoc_insertion_point(class_scope:Dog)
  ))
_sym_db.RegisterMessage(Dog)


# @@protoc_insertion_point(module_scope)
